import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/desktoptwentythree">DesktopTwentyThree</Link>
        </li>
        <li>
          <Link to="/desktopeighteen">DesktopEighteen</Link>
        </li>
        <li>
          <Link to="/desktoptwentyfour">DesktopTwentyFour</Link>
        </li>
        <li>
          <Link to="/desktoptwentyfive">DesktopTwentyFive</Link>
        </li>
        <li>
          <Link to="/desktoptwentytwo">DesktopTwentyTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
